const FETCH_REPOSITORIES_REQUEST = 'FETCH_REPOSITORIES_REQUEST';
const FETCH_REPOSITORIES_SUCCESS = 'FETCH_REPOSITORIES_SUCCESS';
const FETCH_REPOSITORIES_FAILURE = 'FETCH_REPOSITORIES_FAILURE';
const FILTER_REPOSITORIES = 'FILTER_REPOSITORIES';

export default {
  FETCH_REPOSITORIES_REQUEST,
  FETCH_REPOSITORIES_SUCCESS,
  FETCH_REPOSITORIES_FAILURE,
  FILTER_REPOSITORIES
};
